### ISSUE TITLE
Firefox? WebExtensions?

### ISSUE THREAD

**Issue by johnnyasantoss** [Casa/Casa-Extension#1]
Hello!
Nice work open sourcing all of these nice tools :)

Are there any ideas in mind to push a Firefox version of this extension? 

PS: You should definetily consider using [WebExtensions](https://developer.mozilla.org/en-US/docs/Glossary/WebExtensions) (more info [here](https://github.com/Fyrd/caniuse/issues/2271), [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json#Browser_compatibility) and last but not least, [here](https://browserext.github.io/browserext/))

**Comment by johnnyasantoss** [comment]
Nice! Is there a tracker of these bugs for this extension?
Thanks for the info, I'll start using it :)

**Comment by ben-kaufman** [comment]
I opened a PR #2 to fix the Firefox specific issue which caused the extension not to work on it. I suggest to close this issue if and after the PR is merged.
